########### START SELL KIOSK COMPATIBILITY APP DATARUNNER (UEX, SC-TRADE TOOLS) ########### 
shop_ui_commodities=Commodities
shop_ui_commodity=Commodity
shop_ui_commodity_cargo=Commodity Cargo
shop_ui_CommodityKiosk_ShopQuantity=Shop Quantity
shop_ui_CommodityKiosk_ShopInventory=Shop Inventory
shop_ui_CommodityKiosk_YourInventories=Your Inventories
shop_ui_CommodityKiosk_ShopTab_Demand=Local Market Value
shop_ui_CommodityKiosk_ShopTab_Supply=Buy
shop_ui_CommodityKiosk_Supply_Critical=Max Inventory
shop_ui_CommodityKiosk_Supply_Emergent=Inventory Updating
shop_ui_CommodityKiosk_Supply_High=High Inventory
shop_ui_CommodityKiosk_Supply_Low=Low Inventory
shop_ui_CommodityKiosk_Supply_Medium=Medium Inventory
shop_ui_CommodityKiosk_Supply_None=No Inventory
shop_ui_CommodityKiosk_Supply_VeryHigh=Very High Inventory
shop_ui_CommodityKiosk_Supply_VeryLow=Very Low Inventory
shop_ui_CommodityKiosk_Demand_Critical=Out of Stock
shop_ui_CommodityKiosk_Demand_Emergent=Inventory Updating
shop_ui_CommodityKiosk_Demand_High=Low Inventory
shop_ui_CommodityKiosk_Demand_Low=High Inventory
shop_ui_CommodityKiosk_Demand_Medium=Medium Inventory
shop_ui_CommodityKiosk_Demand_None=Max Inventory
shop_ui_CommodityKiosk_Demand_VeryHigh=Very Low Inventory
shop_ui_CommodityKiosk_Demand_VeryLow=Very High Inventory
shop_ui_CommodityKiosk_AvailableCargoSizes=Available Cargo Size (SCU)
shop_ui_CommodityKiosk_NoDemand=No Demand
shop_ui_CommodityKiosk_NoMarket=Cannot Sell
shop_ui_CommodityKiosk_NoStock=Out Of Stock
shop_ui_CommodityKiosk_InStock=In Stock
shop_ui_CommodityKiosk_InDemand=In Demand
kiosk_Sell=Sell
kiosk_Buy=Buy
########### END SELL KIOSK COMPATIBILITY APP DATARUNNER (UEX, SC-TRADE TOOLS) ########### 