########### START HAULER OBJECTIVE COMPATIBILITY (https://hauler.thespacecoder.space/) ########### 
hauling_collect_objective=Collect ~mission(item) from ~mission(location).
hauling_deliver_resource_objective=Deliver ~mission(amount)/~mission(total) SCU of ~mission(item) to ~mission(Destination|Address|ListAll).
hauling_return_resource_objective,P=Deliver ~mission(amount)/~mission(total) SCU of ~mission(item).
########### END HAULER OBJECTIVE COMPATIBILITY (https://hauler.thespacecoder.space/) ########### 